'use strict';

// Generated by tools/gen_nodes.py — do not edit by hand.
module.exports = function (RED) {
    var urlModule = require('url');

    var READONLY_FIELDS       = ["id", "lastUpdate", "pocetPriloh", "createdDate", "updatedBy", "createdBy"];
    var MANDATORY_FIELDS      = ["kod", "nazev"];
    var SUMMARY_FIELDS        = ["id", "lastUpdate", "kod", "nazev", "firma", "mena"];
    var GDPR_FIELDS           = [];
    var BUSINESS_LOGIC_FIELDS = ["id", "lastUpdate", "kod", "nazev", "platiOd", "platiDo", "rozsah", "nakladyPredpoklad", "zaruka", "firma", "typZakazky"];
    var SCHEMA                = {
        "id": {
            "type": "integer",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "lastUpdate": {
            "type": "datetime",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "kod": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 30
        },
        "nazev": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 255
        },
        "nazevA": {
            "type": "string",
            "maxLength": 255
        },
        "nazevB": {
            "type": "string",
            "maxLength": 255
        },
        "nazevC": {
            "type": "string",
            "maxLength": 255
        },
        "poznam": {
            "type": "string"
        },
        "popis": {
            "type": "string"
        },
        "platiOd": {
            "type": "integer",
            "businessLogic": true,
            "maxValue": 9999.0,
            "minValue": 0.0
        },
        "platiDo": {
            "type": "integer",
            "businessLogic": true,
            "maxValue": 9999.0,
            "minValue": 0.0
        },
        "datZahaj": {
            "type": "date"
        },
        "datKonec": {
            "type": "date"
        },
        "procVyh": {
            "type": "numeric",
            "decimal": 2,
            "digits": 6
        },
        "termin": {
            "type": "datetime"
        },
        "splatDny": {
            "type": "integer",
            "minValue": 0.0
        },
        "rozsah": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19
        },
        "nakladyPredpoklad": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19
        },
        "ziskPredpoklad": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "pocetPriloh": {
            "type": "integer",
            "writable": false
        },
        "varSym": {
            "type": "string",
            "maxLength": 30
        },
        "stitky": {
            "type": "string"
        },
        "cisObj": {
            "type": "string",
            "maxLength": 30
        },
        "cisSml": {
            "type": "string",
            "maxLength": 30
        },
        "datZahajPlan": {
            "type": "date"
        },
        "datPredaniPlan": {
            "type": "date"
        },
        "datPredani": {
            "type": "date"
        },
        "zaruka": {
            "type": "logic",
            "businessLogic": true
        },
        "datZaruky": {
            "type": "date"
        },
        "createdDate": {
            "type": "datetime",
            "writable": false
        },
        "firma": {
            "type": "relation",
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20,
            "fkEvidencePath": "adresar"
        },
        "mistUrc": {
            "type": "relation",
            "fkEvidencePath": "misto-urceni"
        },
        "stredisko": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "stredisko"
        },
        "stavZakazky": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "stav-zakazky"
        },
        "typZakazky": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 20,
            "fkEvidencePath": "typ-zakazky"
        },
        "zodpPrac": {
            "type": "relation",
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "vyhZakazky": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "hodnoceni-zakazky"
        },
        "kontaktOsoba": {
            "type": "relation",
            "fkEvidencePath": "kontakt"
        },
        "mena": {
            "type": "relation",
            "inSummary": true,
            "fkEvidencePath": "mena"
        },
        "updatedBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "createdBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        }
    };

    function fetchRecord(serverConfig, evidencePath, id, callback) {
        var baseUrl  = serverConfig.url.replace(/\/$/, '');
        var company  = serverConfig.company;
        var user     = serverConfig.credentials.user     || '';
        var password = serverConfig.credentials.password || '';
        var fullUrl  = baseUrl + '/c/' + company + '/' + evidencePath + '/' + id + '.json';

        var parsed   = urlModule.parse(fullUrl);
        var protocol = parsed.protocol === 'https:' ? require('https') : require('http');
        var auth     = Buffer.from(user + ':' + password).toString('base64');

        var req = protocol.request({
            hostname:           parsed.hostname,
            port:               parsed.port,
            path:               parsed.path,
            method:             'GET',
            headers:            { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' },
            rejectUnauthorized: false
        }, function (res) {
            var data = '';
            res.on('data', function (chunk) { data += chunk; });
            res.on('end', function () {
                if (res.statusCode >= 400) {
                    callback(new Error('HTTP ' + res.statusCode + ' (' + fullUrl + ')'));
                    return;
                }
                try { callback(null, JSON.parse(data)); }
                catch (e) { callback(e); }
            });
        });
        req.on('error', callback);
        req.end();
    }

    function filterKeys(record, allowList) {
        var out = {};
        allowList.forEach(function (k) { if (k in record) out[k] = record[k]; });
        return out;
    }

    function excludeKeys(record, denyList) {
        var out = {};
        Object.keys(record).forEach(function (k) {
            if (denyList.indexOf(k) === -1) out[k] = record[k];
        });
        return out;
    }

    function AbraFlexiZakazkaNode(config) {
        RED.nodes.createNode(this, config);
        var node         = this;
        var serverConfig = RED.nodes.getNode(config.server);

        node.on('input', function (msg, send, done) {
            if (!serverConfig) {
                node.error('Není nakonfigurován AbraFlexi server', msg);
                return done();
            }
            var id = String((msg.payload && msg.payload.id != null ? msg.payload.id : msg.id) || '').trim();
            if (!id) {
                node.error('Chybí msg.payload.id nebo msg.id (ID záznamu)', msg);
                return done();
            }

            node.status({ fill: 'blue', shape: 'dot', text: 'načítám ' + id });

            fetchRecord(serverConfig, 'zakazka', id, function (err, json) {
                if (err) {
                    node.error(err.message, msg);
                    node.status({ fill: 'red', shape: 'ring', text: 'chyba' });
                    return done(err);
                }
                var records = json.winstrom && json.winstrom['zakazka'];
                if (!records || records.length === 0) {
                    node.warn('Záznam nenalezen: zakazka/' + id, msg);
                    node.status({ fill: 'yellow', shape: 'ring', text: 'nenalezeno' });
                    return done();
                }
                var record = records[0];

                var outMsg                  = RED.util.cloneMessage(msg);
                outMsg.payload              = record;
                outMsg.writablePayload      = excludeKeys(record, READONLY_FIELDS);
                outMsg.summaryPayload       = filterKeys(record, SUMMARY_FIELDS);
                outMsg.schema               = SCHEMA;
                outMsg.readonlyFields       = READONLY_FIELDS;
                outMsg.mandatoryFields      = MANDATORY_FIELDS;
                outMsg.gdprFields           = GDPR_FIELDS;
                outMsg.businessLogicFields  = BUSINESS_LOGIC_FIELDS;
                outMsg.topic                = 'zakazka';
                outMsg.abraflexi_id         = record.id || id;

                send([outMsg]);
                node.status({ fill: 'green', shape: 'dot', text: record.kod || String(id) });
                done();
            });
        });

        node.status({ fill: 'grey', shape: 'ring', text: 'čeká' });
    }

    RED.nodes.registerType('abraflexi-zakazka', AbraFlexiZakazkaNode);
};
