'use strict';

// Generated by tools/gen_nodes.py — do not edit by hand.
module.exports = function (RED) {
    var urlModule = require('url');

    var READONLY_FIELDS       = ["id", "lastUpdate", "pocetPriloh", "sada", "createdDate", "updatedBy", "createdBy", "sumStavMj", "sumRezerMj", "sumPozadavkyMj", "sumDostupMj", "cenaZaklBezDph", "cenaZaklVcDph"];
    var MANDATORY_FIELDS      = ["kod", "nazev", "typZasobyK", "typVypoctuHlidatMinK"];
    var SUMMARY_FIELDS        = ["id", "lastUpdate", "kod", "nazev", "cenaZaklBezDph", "cenaZaklVcDph", "cenaZakl"];
    var GDPR_FIELDS           = [];
    var BUSINESS_LOGIC_FIELDS = ["id", "lastUpdate", "kod", "nazev", "platiOd", "platiDo", "typCenyDphK", "procZakl", "individCena", "limMnoz2", "limMnoz3", "limMnoz4", "limMnoz5", "procento2", "procento3", "procento4", "procento5", "zaokrJakK", "zaokrNaK", "typSzbDphK", "nakupCena", "typCenyVychoziK", "typVypCenyK", "typCenyVychozi25K", "typVypCeny25K", "evidVyrCis", "skladove", "typZasobyK", "inEvid", "minMarzeCenik", "evidSarze", "evidExpir", "skupZboz", "stat", "cenaZakl"];
    var SCHEMA                = {
        "id": {
            "type": "integer",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "lastUpdate": {
            "type": "datetime",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "kod": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 64
        },
        "nazev": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 255
        },
        "nazevA": {
            "type": "string",
            "maxLength": 255
        },
        "nazevB": {
            "type": "string",
            "maxLength": 255
        },
        "nazevC": {
            "type": "string",
            "maxLength": 255
        },
        "poznam": {
            "type": "string"
        },
        "popis": {
            "type": "string"
        },
        "platiOd": {
            "type": "integer",
            "businessLogic": true,
            "maxValue": 9999.0,
            "minValue": 0.0
        },
        "platiDo": {
            "type": "integer",
            "businessLogic": true,
            "maxValue": 9999.0,
            "minValue": 0.0
        },
        "eanKod": {
            "type": "string",
            "maxLength": 20
        },
        "kodPlu": {
            "type": "string",
            "maxLength": 20
        },
        "typCenyDphK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "procZakl": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 6
        },
        "individCena": {
            "type": "logic",
            "businessLogic": true
        },
        "limMnoz2": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19,
            "minValue": 0.0
        },
        "limMnoz3": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19,
            "minValue": 0.0
        },
        "limMnoz4": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19,
            "minValue": 0.0
        },
        "limMnoz5": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19,
            "minValue": 0.0
        },
        "procento2": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 6
        },
        "procento3": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 6
        },
        "procento4": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 6
        },
        "procento5": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 6
        },
        "cena2": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "cena3": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "cena4": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "cena5": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "zaokrJakK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "zaokrNaK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "typSzbDphK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "desetinMj": {
            "type": "integer",
            "maxValue": 6.0,
            "minValue": 0.0
        },
        "nakupCena": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19
        },
        "cenJednotka": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "typCenyVychoziK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "typVypCenyK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "typCenyVychozi25K": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "typVypCeny25K": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "evidVyrCis": {
            "type": "logic",
            "businessLogic": true
        },
        "unikVyrCis": {
            "type": "logic"
        },
        "zaruka": {
            "type": "integer"
        },
        "mjZarukyK": {
            "type": "select",
            "maxLength": 50
        },
        "mjKoef2": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "mjKoef3": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "prodejMj": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "hmotMj": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "hmotObal": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "objem": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "zatrid": {
            "type": "string",
            "maxLength": 255
        },
        "skladove": {
            "type": "logic",
            "businessLogic": true
        },
        "typZasobyK": {
            "type": "select",
            "mandatory": true,
            "businessLogic": true
        },
        "baleniNazev1": {
            "type": "string",
            "maxLength": 255
        },
        "baleniNazev2": {
            "type": "string",
            "maxLength": 255
        },
        "baleniNazev3": {
            "type": "string",
            "maxLength": 255
        },
        "baleniNazev4": {
            "type": "string",
            "maxLength": 255
        },
        "baleniNazev5": {
            "type": "string",
            "maxLength": 255
        },
        "baleniMj1": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "baleniMj2": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "baleniMj3": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "baleniMj4": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "baleniMj5": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "baleniEan1": {
            "type": "string",
            "maxLength": 20
        },
        "baleniEan2": {
            "type": "string",
            "maxLength": 20
        },
        "baleniEan3": {
            "type": "string",
            "maxLength": 20
        },
        "baleniEan4": {
            "type": "string",
            "maxLength": 20
        },
        "baleniEan5": {
            "type": "string",
            "maxLength": 20
        },
        "inEvid": {
            "type": "logic",
            "businessLogic": true
        },
        "inKoefMj": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "inKoefStat": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "inKodSled": {
            "type": "string",
            "maxLength": 50
        },
        "popisA": {
            "type": "string"
        },
        "popisB": {
            "type": "string"
        },
        "popisC": {
            "type": "string"
        },
        "cenaBezna": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "stitky": {
            "type": "string"
        },
        "stavy": {
            "type": "string"
        },
        "pocetPriloh": {
            "type": "integer",
            "writable": false
        },
        "exportNaEshop": {
            "type": "logic"
        },
        "minMarzeCenik": {
            "type": "logic",
            "businessLogic": true
        },
        "minMarze": {
            "type": "numeric",
            "decimal": 2,
            "digits": 6
        },
        "typVypoctuHlidatMinK": {
            "type": "select",
            "mandatory": true,
            "maxLength": 50
        },
        "evidSarze": {
            "type": "logic",
            "businessLogic": true
        },
        "evidExpir": {
            "type": "logic",
            "businessLogic": true
        },
        "sada": {
            "type": "logic",
            "writable": false
        },
        "dnyTrvanPoExpir": {
            "type": "integer"
        },
        "neseskupovatObj": {
            "type": "logic"
        },
        "kratkyPopis": {
            "type": "string"
        },
        "klicSlova": {
            "type": "string",
            "maxLength": 255
        },
        "techParam": {
            "type": "string"
        },
        "dodaciLhuta": {
            "type": "numeric",
            "decimal": 6,
            "digits": 19
        },
        "prodejKasa": {
            "type": "logic"
        },
        "kodGenerated": {
            "type": "logic"
        },
        "createdDate": {
            "type": "datetime",
            "writable": false
        },
        "skupZboz": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "skupina-zbozi"
        },
        "mj1": {
            "type": "relation",
            "fkEvidencePath": "merna-jednotka"
        },
        "mj2": {
            "type": "relation",
            "fkEvidencePath": "merna-jednotka"
        },
        "mj3": {
            "type": "relation",
            "fkEvidencePath": "merna-jednotka"
        },
        "mjHmot": {
            "type": "relation",
            "fkEvidencePath": "merna-jednotka"
        },
        "mjObj": {
            "type": "relation",
            "fkEvidencePath": "merna-jednotka"
        },
        "stat": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 3,
            "fkEvidencePath": "stat"
        },
        "nomen": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "intrastat-kod-nomenklatury"
        },
        "dodavatel": {
            "type": "relation",
            "fkEvidencePath": "adresar"
        },
        "vyrobce": {
            "type": "relation",
            "fkEvidencePath": "adresar"
        },
        "dphPren": {
            "type": "relation",
            "fkEvidencePath": "preneseni-dph"
        },
        "mjDodaciLhuta": {
            "type": "relation",
            "fkEvidencePath": "merna-jednotka"
        },
        "updatedBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "createdBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "sumStavMj": {
            "type": "numeric",
            "writable": false,
            "decimal": 6,
            "digits": 19
        },
        "sumRezerMj": {
            "type": "numeric",
            "writable": false,
            "decimal": 6,
            "digits": 19
        },
        "sumPozadavkyMj": {
            "type": "numeric",
            "writable": false,
            "decimal": 6,
            "digits": 19
        },
        "sumDostupMj": {
            "type": "numeric",
            "writable": false,
            "decimal": 6,
            "digits": 19
        },
        "cenaZaklBezDph": {
            "type": "numeric",
            "writable": false,
            "inSummary": true,
            "decimal": 6,
            "digits": 19
        },
        "cenaZaklVcDph": {
            "type": "numeric",
            "writable": false,
            "inSummary": true,
            "decimal": 6,
            "digits": 19
        },
        "cenaZakl": {
            "type": "numeric",
            "businessLogic": true,
            "inSummary": true,
            "decimal": 6,
            "digits": 19
        }
    };

    function fetchRecord(serverConfig, evidencePath, id, callback) {
        var baseUrl  = serverConfig.url.replace(/\/$/, '');
        var company  = serverConfig.company;
        var user     = serverConfig.credentials.user     || '';
        var password = serverConfig.credentials.password || '';
        var fullUrl  = baseUrl + '/c/' + company + '/' + evidencePath + '/' + id + '.json';

        var parsed   = urlModule.parse(fullUrl);
        var protocol = parsed.protocol === 'https:' ? require('https') : require('http');
        var auth     = Buffer.from(user + ':' + password).toString('base64');

        var req = protocol.request({
            hostname:           parsed.hostname,
            port:               parsed.port,
            path:               parsed.path,
            method:             'GET',
            headers:            { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' },
            rejectUnauthorized: false
        }, function (res) {
            var data = '';
            res.on('data', function (chunk) { data += chunk; });
            res.on('end', function () {
                if (res.statusCode >= 400) {
                    callback(new Error('HTTP ' + res.statusCode + ' (' + fullUrl + ')'));
                    return;
                }
                try { callback(null, JSON.parse(data)); }
                catch (e) { callback(e); }
            });
        });
        req.on('error', callback);
        req.end();
    }

    function filterKeys(record, allowList) {
        var out = {};
        allowList.forEach(function (k) { if (k in record) out[k] = record[k]; });
        return out;
    }

    function excludeKeys(record, denyList) {
        var out = {};
        Object.keys(record).forEach(function (k) {
            if (denyList.indexOf(k) === -1) out[k] = record[k];
        });
        return out;
    }

    function AbraFlexiCenikNode(config) {
        RED.nodes.createNode(this, config);
        var node         = this;
        var serverConfig = RED.nodes.getNode(config.server);

        node.on('input', function (msg, send, done) {
            if (!serverConfig) {
                node.error('Není nakonfigurován AbraFlexi server', msg);
                return done();
            }
            var id = String((msg.payload && msg.payload.id != null ? msg.payload.id : msg.id) || '').trim();
            if (!id) {
                node.error('Chybí msg.payload.id nebo msg.id (ID záznamu)', msg);
                return done();
            }

            node.status({ fill: 'blue', shape: 'dot', text: 'načítám ' + id });

            fetchRecord(serverConfig, 'cenik', id, function (err, json) {
                if (err) {
                    node.error(err.message, msg);
                    node.status({ fill: 'red', shape: 'ring', text: 'chyba' });
                    return done(err);
                }
                var records = json.winstrom && json.winstrom['cenik'];
                if (!records || records.length === 0) {
                    node.warn('Záznam nenalezen: cenik/' + id, msg);
                    node.status({ fill: 'yellow', shape: 'ring', text: 'nenalezeno' });
                    return done();
                }
                var record = records[0];

                var outMsg                  = RED.util.cloneMessage(msg);
                outMsg.payload              = record;
                outMsg.writablePayload      = excludeKeys(record, READONLY_FIELDS);
                outMsg.summaryPayload       = filterKeys(record, SUMMARY_FIELDS);
                outMsg.schema               = SCHEMA;
                outMsg.readonlyFields       = READONLY_FIELDS;
                outMsg.mandatoryFields      = MANDATORY_FIELDS;
                outMsg.gdprFields           = GDPR_FIELDS;
                outMsg.businessLogicFields  = BUSINESS_LOGIC_FIELDS;
                outMsg.topic                = 'cenik';
                outMsg.abraflexi_id         = record.id || id;

                send([outMsg]);
                node.status({ fill: 'green', shape: 'dot', text: record.kod || String(id) });
                done();
            });
        });

        node.status({ fill: 'grey', shape: 'ring', text: 'čeká' });
    }

    RED.nodes.registerType('abraflexi-cenik', AbraFlexiCenikNode);
};
