'use strict';

// Generated by tools/gen_nodes.py — do not edit by hand.
module.exports = function (RED) {
    var urlModule = require('url');

    var READONLY_FIELDS       = ["id", "lastUpdate", "pocetPriloh", "createdDate", "updatedBy", "createdBy"];
    var MANDATORY_FIELDS      = [];
    var SUMMARY_FIELDS        = ["id", "lastUpdate", "tel", "mobil", "email", "prijmeni", "jmeno", "funkce", "firma"];
    var GDPR_FIELDS           = ["ulice", "mesto", "psc", "tel", "mobil", "fax", "email", "prijmeni", "jmeno", "osloveni", "titul", "titulZa", "datNaroz", "rodCis"];
    var BUSINESS_LOGIC_FIELDS = ["id", "lastUpdate", "stat", "primarni", "rodCis", "firma"];
    var SCHEMA                = {
        "id": {
            "type": "integer",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "lastUpdate": {
            "type": "datetime",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "ulice": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "mesto": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "psc": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "stat": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 3,
            "fkEvidencePath": "stat"
        },
        "region": {
            "type": "relation",
            "fkEvidencePath": "region"
        },
        "tel": {
            "type": "string",
            "gdpr": true,
            "inSummary": true,
            "maxLength": 255
        },
        "mobil": {
            "type": "string",
            "gdpr": true,
            "inSummary": true,
            "maxLength": 255
        },
        "fax": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "email": {
            "type": "string",
            "gdpr": true,
            "inSummary": true,
            "maxLength": 255
        },
        "www": {
            "type": "string",
            "maxLength": 255
        },
        "popis": {
            "type": "string"
        },
        "poznam": {
            "type": "string"
        },
        "prijmeni": {
            "type": "string",
            "gdpr": true,
            "inSummary": true,
            "maxLength": 255
        },
        "jmeno": {
            "type": "string",
            "gdpr": true,
            "inSummary": true,
            "maxLength": 255
        },
        "osloveni": {
            "type": "string",
            "gdpr": true
        },
        "titul": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "titulZa": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "funkce": {
            "type": "string",
            "inSummary": true,
            "maxLength": 255
        },
        "oddeleni": {
            "type": "string"
        },
        "primarni": {
            "type": "logic",
            "businessLogic": true
        },
        "odesilatFak": {
            "type": "logic"
        },
        "odesilatObj": {
            "type": "logic"
        },
        "odesilatNab": {
            "type": "logic"
        },
        "odesilatPpt": {
            "type": "logic"
        },
        "odesilatSkl": {
            "type": "logic"
        },
        "odesilatPok": {
            "type": "logic"
        },
        "datNaroz": {
            "type": "date",
            "gdpr": true
        },
        "rodCis": {
            "type": "string",
            "gdpr": true,
            "businessLogic": true,
            "maxLength": 20
        },
        "stitky": {
            "type": "string"
        },
        "pocetPriloh": {
            "type": "integer",
            "writable": false
        },
        "username": {
            "type": "string",
            "maxLength": 255
        },
        "password": {
            "type": "string",
            "maxLength": 255
        },
        "blocked": {
            "type": "logic"
        },
        "blockedText": {
            "type": "string"
        },
        "createdDate": {
            "type": "datetime",
            "writable": false
        },
        "firma": {
            "type": "relation",
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20,
            "fkEvidencePath": "adresar"
        },
        "updatedBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "createdBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        }
    };

    function fetchRecord(serverConfig, evidencePath, id, callback) {
        var baseUrl  = serverConfig.url.replace(/\/$/, '');
        var company  = serverConfig.company;
        var user     = serverConfig.credentials.user     || '';
        var password = serverConfig.credentials.password || '';
        var fullUrl  = baseUrl + '/c/' + company + '/' + evidencePath + '/' + id + '.json';

        var parsed   = urlModule.parse(fullUrl);
        var protocol = parsed.protocol === 'https:' ? require('https') : require('http');
        var auth     = Buffer.from(user + ':' + password).toString('base64');

        var req = protocol.request({
            hostname:           parsed.hostname,
            port:               parsed.port,
            path:               parsed.path,
            method:             'GET',
            headers:            { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' },
            rejectUnauthorized: false
        }, function (res) {
            var data = '';
            res.on('data', function (chunk) { data += chunk; });
            res.on('end', function () {
                if (res.statusCode >= 400) {
                    callback(new Error('HTTP ' + res.statusCode + ' (' + fullUrl + ')'));
                    return;
                }
                try { callback(null, JSON.parse(data)); }
                catch (e) { callback(e); }
            });
        });
        req.on('error', callback);
        req.end();
    }

    function filterKeys(record, allowList) {
        var out = {};
        allowList.forEach(function (k) { if (k in record) out[k] = record[k]; });
        return out;
    }

    function excludeKeys(record, denyList) {
        var out = {};
        Object.keys(record).forEach(function (k) {
            if (denyList.indexOf(k) === -1) out[k] = record[k];
        });
        return out;
    }

    function AbraFlexiKontaktNode(config) {
        RED.nodes.createNode(this, config);
        var node         = this;
        var serverConfig = RED.nodes.getNode(config.server);

        node.on('input', function (msg, send, done) {
            if (!serverConfig) {
                node.error('Není nakonfigurován AbraFlexi server', msg);
                return done();
            }
            var id = String((msg.payload && msg.payload.id != null ? msg.payload.id : msg.id) || '').trim();
            if (!id) {
                node.error('Chybí msg.payload.id nebo msg.id (ID záznamu)', msg);
                return done();
            }

            node.status({ fill: 'blue', shape: 'dot', text: 'načítám ' + id });

            fetchRecord(serverConfig, 'kontakt', id, function (err, json) {
                if (err) {
                    node.error(err.message, msg);
                    node.status({ fill: 'red', shape: 'ring', text: 'chyba' });
                    return done(err);
                }
                var records = json.winstrom && json.winstrom['kontakt'];
                if (!records || records.length === 0) {
                    node.warn('Záznam nenalezen: kontakt/' + id, msg);
                    node.status({ fill: 'yellow', shape: 'ring', text: 'nenalezeno' });
                    return done();
                }
                var record = records[0];

                var outMsg                  = RED.util.cloneMessage(msg);
                outMsg.payload              = record;
                outMsg.writablePayload      = excludeKeys(record, READONLY_FIELDS);
                outMsg.summaryPayload       = filterKeys(record, SUMMARY_FIELDS);
                outMsg.schema               = SCHEMA;
                outMsg.readonlyFields       = READONLY_FIELDS;
                outMsg.mandatoryFields      = MANDATORY_FIELDS;
                outMsg.gdprFields           = GDPR_FIELDS;
                outMsg.businessLogicFields  = BUSINESS_LOGIC_FIELDS;
                outMsg.topic                = 'kontakt';
                outMsg.abraflexi_id         = record.id || id;

                send([outMsg]);
                node.status({ fill: 'green', shape: 'dot', text: record.kod || String(id) });
                done();
            });
        });

        node.status({ fill: 'grey', shape: 'ring', text: 'čeká' });
    }

    RED.nodes.registerType('abraflexi-kontakt', AbraFlexiKontaktNode);
};
