'use strict';

// Generated by tools/gen_nodes.py — do not edit by hand.
module.exports = function (RED) {
    var urlModule = require('url');

    var READONLY_FIELDS       = ["id", "lastUpdate", "datUdalZar", "zamekK", "pocetPriloh", "uzivatel"];
    var MANDATORY_FIELDS      = ["kod", "nazev", "kusySoubor", "druhK", "datKoupe", "datZar", "techZhod", "typMajetku", "stredisko"];
    var SUMMARY_FIELDS        = ["id", "lastUpdate", "kod", "nazev"];
    var GDPR_FIELDS           = [];
    var BUSINESS_LOGIC_FIELDS = ["id", "lastUpdate", "kod", "platiOd", "platiDo", "cena", "druhK", "datKoupe", "datZar", "stariPor", "techZhod", "datZacDan", "datZacUcet", "zpusOdpK", "nahrUcetOdpK", "uctovatZar", "typMajetku"];
    var SCHEMA                = {
        "id": {
            "type": "integer",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "lastUpdate": {
            "type": "datetime",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "kod": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20
        },
        "nazev": {
            "type": "string",
            "mandatory": true,
            "inSummary": true,
            "maxLength": 255
        },
        "nazevA": {
            "type": "string",
            "maxLength": 255
        },
        "nazevB": {
            "type": "string",
            "maxLength": 255
        },
        "nazevC": {
            "type": "string",
            "maxLength": 255
        },
        "poznam": {
            "type": "string"
        },
        "popis": {
            "type": "string"
        },
        "platiOd": {
            "type": "integer",
            "businessLogic": true,
            "maxValue": 9999.0,
            "minValue": 0.0
        },
        "platiDo": {
            "type": "integer",
            "businessLogic": true,
            "maxValue": 9999.0,
            "minValue": 0.0
        },
        "cena": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15,
            "minValue": 0.0
        },
        "kusySoubor": {
            "type": "integer",
            "mandatory": true,
            "minValue": 1.0
        },
        "druhK": {
            "type": "select",
            "mandatory": true,
            "businessLogic": true,
            "maxLength": 50
        },
        "cidPoriz": {
            "type": "string",
            "maxLength": 20
        },
        "zpusPor": {
            "type": "string",
            "maxLength": 255
        },
        "datKoupe": {
            "type": "date",
            "mandatory": true,
            "businessLogic": true
        },
        "datVyroby": {
            "type": "date"
        },
        "vyrCis": {
            "type": "string",
            "maxLength": 20
        },
        "mjZarukyK": {
            "type": "select",
            "maxLength": 50
        },
        "zaruka": {
            "type": "integer"
        },
        "datZar": {
            "type": "date",
            "mandatory": true,
            "businessLogic": true
        },
        "stariPor": {
            "type": "integer",
            "businessLogic": true,
            "minValue": 0.0
        },
        "zustUcet": {
            "type": "numeric",
            "decimal": 2,
            "digits": 15,
            "minValue": 0.0
        },
        "zustDan": {
            "type": "numeric",
            "decimal": 2,
            "digits": 15,
            "minValue": 0.0
        },
        "techZhod": {
            "type": "logic",
            "mandatory": true,
            "businessLogic": true
        },
        "datZacDan": {
            "type": "date",
            "businessLogic": true
        },
        "datZacUcet": {
            "type": "date",
            "businessLogic": true
        },
        "zpusOdpK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "zvysZrychK": {
            "type": "select",
            "maxLength": 50
        },
        "nahrUcetOdpK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "predpisUcetOdp": {
            "type": "numeric",
            "decimal": 2,
            "digits": 12,
            "minValue": 0.0
        },
        "eanKod": {
            "type": "string",
            "maxLength": 20
        },
        "uctovatZar": {
            "type": "logic",
            "businessLogic": true
        },
        "stariTechZhod": {
            "type": "integer",
            "minValue": 0.0
        },
        "datUdalZar": {
            "type": "date",
            "writable": false
        },
        "datUdalVyr": {
            "type": "date"
        },
        "zamekK": {
            "type": "select",
            "writable": false,
            "maxLength": 50
        },
        "skp": {
            "type": "string",
            "maxLength": 50
        },
        "pocetPriloh": {
            "type": "integer",
            "writable": false
        },
        "stitky": {
            "type": "string"
        },
        "katastrUzemi": {
            "type": "string",
            "maxLength": 255
        },
        "parcela": {
            "type": "string",
            "maxLength": 255
        },
        "vozCislo": {
            "type": "string",
            "maxLength": 255
        },
        "vozSpz": {
            "type": "string",
            "maxLength": 255
        },
        "vozZnacka": {
            "type": "string",
            "maxLength": 255
        },
        "vozModel": {
            "type": "string",
            "maxLength": 255
        },
        "vozTyp": {
            "type": "string",
            "maxLength": 255
        },
        "vozObjem": {
            "type": "numeric",
            "decimal": 2,
            "digits": 15
        },
        "vozHavar": {
            "type": "string",
            "maxLength": 255
        },
        "vozHavarVyse": {
            "type": "numeric",
            "decimal": 2,
            "digits": 15
        },
        "vozVybava": {
            "type": "string"
        },
        "sazba": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "odpisova-skupina"
        },
        "mistnost": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "umisteni"
        },
        "sekce": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "umisteni"
        },
        "objekt": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "umisteni"
        },
        "typMajetku": {
            "type": "relation",
            "mandatory": true,
            "businessLogic": true,
            "maxLength": 20,
            "fkEvidencePath": "typ-majetku"
        },
        "zakazka": {
            "type": "relation",
            "maxLength": 30,
            "fkEvidencePath": "zakazka"
        },
        "stredisko": {
            "type": "relation",
            "mandatory": true,
            "maxLength": 20,
            "fkEvidencePath": "stredisko"
        },
        "doklFak": {
            "type": "relation",
            "fkEvidencePath": "faktura-prijata"
        },
        "dodavatel": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "adresar"
        },
        "vyrobce": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "adresar"
        },
        "primarniUcet": {
            "type": "relation",
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "protiUcetZarazeni": {
            "type": "relation",
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "opravnyUcet": {
            "type": "relation",
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "odpisovyUcet": {
            "type": "relation",
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "zustVyrazUcet": {
            "type": "relation",
            "fkEvidencePath": "ucet"
        },
        "uzivatel": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        }
    };

    function fetchRecord(serverConfig, evidencePath, id, callback) {
        var baseUrl  = serverConfig.url.replace(/\/$/, '');
        var company  = serverConfig.company;
        var user     = serverConfig.credentials.user     || '';
        var password = serverConfig.credentials.password || '';
        var fullUrl  = baseUrl + '/c/' + company + '/' + evidencePath + '/' + id + '.json';

        var parsed   = urlModule.parse(fullUrl);
        var protocol = parsed.protocol === 'https:' ? require('https') : require('http');
        var auth     = Buffer.from(user + ':' + password).toString('base64');

        var req = protocol.request({
            hostname:           parsed.hostname,
            port:               parsed.port,
            path:               parsed.path,
            method:             'GET',
            headers:            { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' },
            rejectUnauthorized: false
        }, function (res) {
            var data = '';
            res.on('data', function (chunk) { data += chunk; });
            res.on('end', function () {
                if (res.statusCode >= 400) {
                    callback(new Error('HTTP ' + res.statusCode + ' (' + fullUrl + ')'));
                    return;
                }
                try { callback(null, JSON.parse(data)); }
                catch (e) { callback(e); }
            });
        });
        req.on('error', callback);
        req.end();
    }

    function filterKeys(record, allowList) {
        var out = {};
        allowList.forEach(function (k) { if (k in record) out[k] = record[k]; });
        return out;
    }

    function excludeKeys(record, denyList) {
        var out = {};
        Object.keys(record).forEach(function (k) {
            if (denyList.indexOf(k) === -1) out[k] = record[k];
        });
        return out;
    }

    function AbraFlexiMajetekNode(config) {
        RED.nodes.createNode(this, config);
        var node         = this;
        var serverConfig = RED.nodes.getNode(config.server);

        node.on('input', function (msg, send, done) {
            if (!serverConfig) {
                node.error('Není nakonfigurován AbraFlexi server', msg);
                return done();
            }
            var id = String((msg.payload && msg.payload.id != null ? msg.payload.id : msg.id) || '').trim();
            if (!id) {
                node.error('Chybí msg.payload.id nebo msg.id (ID záznamu)', msg);
                return done();
            }

            node.status({ fill: 'blue', shape: 'dot', text: 'načítám ' + id });

            fetchRecord(serverConfig, 'majetek', id, function (err, json) {
                if (err) {
                    node.error(err.message, msg);
                    node.status({ fill: 'red', shape: 'ring', text: 'chyba' });
                    return done(err);
                }
                var records = json.winstrom && json.winstrom['majetek'];
                if (!records || records.length === 0) {
                    node.warn('Záznam nenalezen: majetek/' + id, msg);
                    node.status({ fill: 'yellow', shape: 'ring', text: 'nenalezeno' });
                    return done();
                }
                var record = records[0];

                var outMsg                  = RED.util.cloneMessage(msg);
                outMsg.payload              = record;
                outMsg.writablePayload      = excludeKeys(record, READONLY_FIELDS);
                outMsg.summaryPayload       = filterKeys(record, SUMMARY_FIELDS);
                outMsg.schema               = SCHEMA;
                outMsg.readonlyFields       = READONLY_FIELDS;
                outMsg.mandatoryFields      = MANDATORY_FIELDS;
                outMsg.gdprFields           = GDPR_FIELDS;
                outMsg.businessLogicFields  = BUSINESS_LOGIC_FIELDS;
                outMsg.topic                = 'majetek';
                outMsg.abraflexi_id         = record.id || id;

                send([outMsg]);
                node.status({ fill: 'green', shape: 'dot', text: record.kod || String(id) });
                done();
            });
        });

        node.status({ fill: 'grey', shape: 'ring', text: 'čeká' });
    }

    RED.nodes.registerType('abraflexi-majetek', AbraFlexiMajetekNode);
};
