'use strict';

// Generated by tools/gen_nodes.py — do not edit by hand.
module.exports = function (RED) {
    var urlModule = require('url');

    var READONLY_FIELDS       = ["id", "lastUpdate", "pocetPriloh", "typDoklFakSplatDny", "poslDatSplat", "firma_nazev", "typDoklFakStredisko", "typDoklFakCinnost", "typDoklFakBspBan"];
    var MANDATORY_FIELDS      = ["kod", "nazev", "smlouvaOd", "typSml", "firma"];
    var SUMMARY_FIELDS        = ["id", "lastUpdate", "kod", "nazev", "popis", "poslDatSplat", "firma"];
    var GDPR_FIELDS           = [];
    var BUSINESS_LOGIC_FIELDS = ["id", "lastUpdate", "kod", "smlouvaOd", "ignorovatTypSml", "typSml", "firma", "zakazka", "typDoklFak"];
    var SCHEMA                = {
        "id": {
            "type": "integer",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "lastUpdate": {
            "type": "datetime",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "kod": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20
        },
        "nazev": {
            "type": "string",
            "mandatory": true,
            "inSummary": true,
            "maxLength": 255
        },
        "nazevA": {
            "type": "string",
            "maxLength": 255
        },
        "nazevB": {
            "type": "string",
            "maxLength": 255
        },
        "nazevC": {
            "type": "string",
            "maxLength": 255
        },
        "poznam": {
            "type": "string"
        },
        "popis": {
            "type": "string",
            "inSummary": true
        },
        "sablona": {
            "type": "logic"
        },
        "smlouvaOd": {
            "type": "date",
            "mandatory": true,
            "businessLogic": true
        },
        "smlouvaDo": {
            "type": "date"
        },
        "datumPodepsani": {
            "type": "date"
        },
        "datumUcinnosti": {
            "type": "date"
        },
        "frekFakt": {
            "type": "integer"
        },
        "den": {
            "type": "integer"
        },
        "mesic": {
            "type": "integer"
        },
        "zpusFaktK": {
            "type": "select",
            "maxLength": 50
        },
        "dnyFakt": {
            "type": "integer"
        },
        "varSym": {
            "type": "string",
            "maxLength": 30
        },
        "cisDosle": {
            "type": "string",
            "maxLength": 40
        },
        "cisSmlProti": {
            "type": "string",
            "maxLength": 50
        },
        "autoGen": {
            "type": "logic"
        },
        "autoMail": {
            "type": "logic"
        },
        "autoProdl": {
            "type": "logic"
        },
        "autoProlong": {
            "type": "integer"
        },
        "autoZakazka": {
            "type": "logic"
        },
        "datVystZDuzp": {
            "type": "logic"
        },
        "generovatNuloveFaktury": {
            "type": "logic"
        },
        "ignorovatTypSml": {
            "type": "logic",
            "businessLogic": true
        },
        "preplatky": {
            "type": "logic"
        },
        "varSymFakt": {
            "type": "logic"
        },
        "stitky": {
            "type": "string"
        },
        "pocetPriloh": {
            "type": "integer",
            "writable": false
        },
        "katastrUzemi": {
            "type": "string",
            "maxLength": 255
        },
        "parcela": {
            "type": "string",
            "maxLength": 255
        },
        "vypovedniLhuta": {
            "type": "integer"
        },
        "datZaloz": {
            "type": "date"
        },
        "datVypoz": {
            "type": "date"
        },
        "typDoklFakSplatDny": {
            "type": "integer",
            "writable": false,
            "minValue": 0.0
        },
        "poslDatSplat": {
            "type": "date",
            "writable": false,
            "inSummary": true
        },
        "firma_nazev": {
            "type": "string",
            "writable": false,
            "maxLength": 255
        },
        "typSml": {
            "type": "relation",
            "mandatory": true,
            "businessLogic": true,
            "fkEvidencePath": "typ-smlouvy"
        },
        "firma": {
            "type": "relation",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "fkEvidencePath": "adresar"
        },
        "firmaFakt": {
            "type": "relation",
            "fkEvidencePath": "adresar"
        },
        "zakazka": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "zakazka"
        },
        "stredisko": {
            "type": "relation",
            "fkEvidencePath": "stredisko"
        },
        "typDoklFak": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "typ-faktury-vydane"
        },
        "konSym": {
            "type": "relation",
            "fkEvidencePath": "konst-symbol"
        },
        "stavSml": {
            "type": "relation",
            "fkEvidencePath": "stav-smlouvy"
        },
        "typDoklFakStredisko": {
            "type": "relation",
            "writable": false,
            "fkEvidencePath": "stredisko"
        },
        "typDoklFakCinnost": {
            "type": "relation",
            "writable": false,
            "fkEvidencePath": "cinnost"
        },
        "typDoklFakBspBan": {
            "type": "relation",
            "writable": false,
            "fkEvidencePath": "bankovni-ucet"
        },
        "zodpOsoba": {
            "type": "relation",
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "kontaktOsoba": {
            "type": "relation",
            "fkEvidencePath": "kontakt"
        }
    };

    function fetchRecord(serverConfig, evidencePath, id, callback) {
        var baseUrl  = serverConfig.url.replace(/\/$/, '');
        var company  = serverConfig.company;
        var user     = serverConfig.credentials.user     || '';
        var password = serverConfig.credentials.password || '';
        var fullUrl  = baseUrl + '/c/' + company + '/' + evidencePath + '/' + id + '.json';

        var parsed   = urlModule.parse(fullUrl);
        var protocol = parsed.protocol === 'https:' ? require('https') : require('http');
        var auth     = Buffer.from(user + ':' + password).toString('base64');

        var req = protocol.request({
            hostname:           parsed.hostname,
            port:               parsed.port,
            path:               parsed.path,
            method:             'GET',
            headers:            { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' },
            rejectUnauthorized: false
        }, function (res) {
            var data = '';
            res.on('data', function (chunk) { data += chunk; });
            res.on('end', function () {
                if (res.statusCode >= 400) {
                    callback(new Error('HTTP ' + res.statusCode + ' (' + fullUrl + ')'));
                    return;
                }
                try { callback(null, JSON.parse(data)); }
                catch (e) { callback(e); }
            });
        });
        req.on('error', callback);
        req.end();
    }

    function filterKeys(record, allowList) {
        var out = {};
        allowList.forEach(function (k) { if (k in record) out[k] = record[k]; });
        return out;
    }

    function excludeKeys(record, denyList) {
        var out = {};
        Object.keys(record).forEach(function (k) {
            if (denyList.indexOf(k) === -1) out[k] = record[k];
        });
        return out;
    }

    function AbraFlexiSmlouvaNode(config) {
        RED.nodes.createNode(this, config);
        var node         = this;
        var serverConfig = RED.nodes.getNode(config.server);

        node.on('input', function (msg, send, done) {
            if (!serverConfig) {
                node.error('Není nakonfigurován AbraFlexi server', msg);
                return done();
            }
            var id = String((msg.payload && msg.payload.id != null ? msg.payload.id : msg.id) || '').trim();
            if (!id) {
                node.error('Chybí msg.payload.id nebo msg.id (ID záznamu)', msg);
                return done();
            }

            node.status({ fill: 'blue', shape: 'dot', text: 'načítám ' + id });

            fetchRecord(serverConfig, 'smlouva', id, function (err, json) {
                if (err) {
                    node.error(err.message, msg);
                    node.status({ fill: 'red', shape: 'ring', text: 'chyba' });
                    return done(err);
                }
                var records = json.winstrom && json.winstrom['smlouva'];
                if (!records || records.length === 0) {
                    node.warn('Záznam nenalezen: smlouva/' + id, msg);
                    node.status({ fill: 'yellow', shape: 'ring', text: 'nenalezeno' });
                    return done();
                }
                var record = records[0];

                var outMsg                  = RED.util.cloneMessage(msg);
                outMsg.payload              = record;
                outMsg.writablePayload      = excludeKeys(record, READONLY_FIELDS);
                outMsg.summaryPayload       = filterKeys(record, SUMMARY_FIELDS);
                outMsg.schema               = SCHEMA;
                outMsg.readonlyFields       = READONLY_FIELDS;
                outMsg.mandatoryFields      = MANDATORY_FIELDS;
                outMsg.gdprFields           = GDPR_FIELDS;
                outMsg.businessLogicFields  = BUSINESS_LOGIC_FIELDS;
                outMsg.topic                = 'smlouva';
                outMsg.abraflexi_id         = record.id || id;

                var subMsg             = RED.util.cloneMessage(msg);
                subMsg.payload = record['smlouva-polozka'] || [];
                subMsg.topic   = 'smlouva-polozka';
                send([outMsg, subMsg]);
                node.status({ fill: 'green', shape: 'dot', text: record.kod || String(id) });
                done();
            });
        });

        node.status({ fill: 'grey', shape: 'ring', text: 'čeká' });
    }

    RED.nodes.registerType('abraflexi-smlouva', AbraFlexiSmlouvaNode);
};
