'use strict';

// Generated by tools/gen_nodes.py — do not edit by hand.
module.exports = function (RED) {
    var urlModule = require('url');

    var READONLY_FIELDS       = ["id", "lastUpdate", "updatedBy", "createdBy", "createdDate", "zamekK", "datUhr", "sumZklCelkem", "sumDphCelkem", "sumZklCelkemMen", "sumDphCelkemMen", "pocetPriloh", "ucetni", "zuctovano", "storno", "uzivatel", "sazbaDphOsv", "sazbaDphSniz", "sazbaDphSniz2", "sazbaDphZakl", "uuid", "podpisPrik", "prikazSum", "prikazSumMen", "juhSum", "juhSumMen", "juhDat", "juhDatMen", "zbyvaUhradit", "zbyvaUhraditMen", "sumZalohy", "sumZalohyMen", "stavOdpocetK"];
    var MANDATORY_FIELDS      = ["kod", "varSym", "datVyst", "datSplat", "typDokl"];
    var SUMMARY_FIELDS        = ["id", "lastUpdate", "kod", "datVyst", "datSplat", "popis", "sumCelkem", "sumCelkemMen", "mena", "firma", "zbyvaUhradit", "zbyvaUhraditMen", "stavUhrK", "sumZalohy", "sumZalohyMen"];
    var GDPR_FIELDS           = ["nazFirmy", "ulice", "mesto", "psc", "region", "kontaktJmeno", "kontaktEmail", "kontaktTel"];
    var BUSINESS_LOGIC_FIELDS = ["id", "lastUpdate", "kod", "zamekK", "cisDosle", "varSym", "cisObj", "datVyst", "duzpPuv", "duzpUcto", "datSplat", "datSazbyDph", "sumOsv", "sumZklSniz", "sumZklSniz2", "sumZklZakl", "sumDphSniz", "sumDphSniz2", "sumDphZakl", "sumCelkSniz", "sumCelkSniz2", "sumCelkZakl", "sumCelkem", "sumOsvMen", "sumZklSnizMen", "sumZklSniz2Men", "sumZklZaklMen", "sumDphZaklMen", "sumDphSnizMen", "sumDphSniz2Men", "sumCelkSnizMen", "sumCelkSniz2Men", "sumCelkZaklMen", "sumCelkemMen", "kurz", "kurzMnozstvi", "dic", "bezPolozek", "ucetni", "szbDphSniz", "szbDphSniz2", "szbDphZakl", "uzpTuzemsko", "datUcto", "storno", "typDokl", "mena", "firma", "stat", "banSpojDod", "bankovniUcet", "typUcOp", "primUcet", "protiUcet", "dphZaklUcet", "dphSnizUcet", "dphSniz2Ucet", "statDph", "clenDph", "stredisko", "cinnost", "zakazka", "kontaktOsoba", "sazbaDphOsv", "sazbaDphSniz", "sazbaDphSniz2", "sazbaDphZakl", "formaDopravy", "clenKonVykDph", "formaUhradyCis", "stavUhrK", "stavOdpocetK", "osobUpravaDph"];
    var SCHEMA                = {
        "id": {
            "type": "integer",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "lastUpdate": {
            "type": "datetime",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "updatedBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "createdBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "createdDate": {
            "type": "datetime",
            "writable": false
        },
        "kod": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20
        },
        "zamekK": {
            "type": "select",
            "writable": false,
            "businessLogic": true,
            "maxLength": 50
        },
        "cisDosle": {
            "type": "string",
            "businessLogic": true,
            "maxLength": 40
        },
        "varSym": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "maxLength": 30
        },
        "cisSml": {
            "type": "string",
            "maxLength": 30
        },
        "cisObj": {
            "type": "string",
            "businessLogic": true,
            "maxLength": 2000
        },
        "datObj": {
            "type": "date"
        },
        "cisDodak": {
            "type": "string",
            "maxLength": 30
        },
        "doprava": {
            "type": "string"
        },
        "datVyst": {
            "type": "date",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true
        },
        "duzpPuv": {
            "type": "date",
            "businessLogic": true
        },
        "duzpUcto": {
            "type": "date",
            "businessLogic": true
        },
        "datSplat": {
            "type": "date",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true
        },
        "datUhr": {
            "type": "date",
            "writable": false
        },
        "datTermin": {
            "type": "date"
        },
        "datReal": {
            "type": "date"
        },
        "datSazbyDph": {
            "type": "date",
            "businessLogic": true
        },
        "popis": {
            "type": "string",
            "inSummary": true,
            "maxLength": 255
        },
        "poznam": {
            "type": "string"
        },
        "sumOsv": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumZklSniz": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumZklSniz2": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumZklZakl": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumZklCelkem": {
            "type": "numeric",
            "writable": false,
            "decimal": 2,
            "digits": 15
        },
        "sumDphSniz": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumDphSniz2": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumDphZakl": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumDphCelkem": {
            "type": "numeric",
            "writable": false,
            "decimal": 2,
            "digits": 15
        },
        "sumCelkSniz": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumCelkSniz2": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumCelkZakl": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumCelkem": {
            "type": "numeric",
            "businessLogic": true,
            "inSummary": true,
            "decimal": 2,
            "digits": 15
        },
        "sumOsvMen": {
            "type": "numeric",
            "businessLogic": true
        },
        "sumZklSnizMen": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumZklSniz2Men": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumZklZaklMen": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumZklCelkemMen": {
            "type": "numeric",
            "writable": false,
            "decimal": 2,
            "digits": 15
        },
        "sumDphZaklMen": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumDphSnizMen": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumDphSniz2Men": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumDphCelkemMen": {
            "type": "numeric",
            "writable": false,
            "decimal": 2,
            "digits": 15
        },
        "sumCelkSnizMen": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumCelkSniz2Men": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumCelkZaklMen": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 15
        },
        "sumCelkemMen": {
            "type": "numeric",
            "businessLogic": true,
            "inSummary": true,
            "decimal": 2,
            "digits": 15
        },
        "kurz": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19
        },
        "kurzMnozstvi": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 6,
            "digits": 19,
            "minValue": 0.0
        },
        "stavUzivK": {
            "type": "select",
            "maxLength": 50
        },
        "nazFirmy": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "ulice": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "mesto": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "psc": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "eanKod": {
            "type": "string",
            "maxLength": 20
        },
        "ic": {
            "type": "string",
            "maxLength": 20
        },
        "dic": {
            "type": "string",
            "businessLogic": true,
            "maxLength": 20
        },
        "pocetPriloh": {
            "type": "integer",
            "writable": false
        },
        "buc": {
            "type": "string",
            "maxLength": 255
        },
        "iban": {
            "type": "string",
            "maxLength": 255
        },
        "bic": {
            "type": "string",
            "maxLength": 255
        },
        "specSym": {
            "type": "string",
            "maxLength": 255
        },
        "bezPolozek": {
            "type": "logic",
            "businessLogic": true
        },
        "ucetni": {
            "type": "logic",
            "writable": false,
            "businessLogic": true
        },
        "szbDphSniz": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 6
        },
        "szbDphSniz2": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 6
        },
        "szbDphZakl": {
            "type": "numeric",
            "businessLogic": true,
            "decimal": 2,
            "digits": 6
        },
        "uzpTuzemsko": {
            "type": "logic",
            "businessLogic": true
        },
        "zuctovano": {
            "type": "logic",
            "writable": false
        },
        "datUcto": {
            "type": "date",
            "businessLogic": true
        },
        "vyloucitSaldo": {
            "type": "logic"
        },
        "storno": {
            "type": "logic",
            "writable": false,
            "businessLogic": true
        },
        "stitky": {
            "type": "string"
        },
        "typDokl": {
            "type": "relation",
            "mandatory": true,
            "businessLogic": true,
            "fkEvidencePath": "typ-zavazku"
        },
        "mena": {
            "type": "relation",
            "businessLogic": true,
            "inSummary": true,
            "fkEvidencePath": "mena"
        },
        "konSym": {
            "type": "relation",
            "fkEvidencePath": "konst-symbol"
        },
        "firma": {
            "type": "relation",
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20,
            "fkEvidencePath": "adresar"
        },
        "stat": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 3,
            "fkEvidencePath": "stat"
        },
        "region": {
            "type": "relation",
            "gdpr": true,
            "fkEvidencePath": "region"
        },
        "banSpojDod": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "adresar-bankovni-ucet"
        },
        "bankovniUcet": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "bankovni-ucet"
        },
        "typUcOp": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "predpis-zauctovani"
        },
        "primUcet": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "protiUcet": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "dphZaklUcet": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "dphSnizUcet": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "dphSniz2Ucet": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 6,
            "fkEvidencePath": "ucet"
        },
        "smerKod": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "penezni-ustav"
        },
        "statDph": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 3,
            "fkEvidencePath": "stat-dph"
        },
        "clenDph": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "cleneni-dph"
        },
        "stredisko": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 20,
            "fkEvidencePath": "stredisko"
        },
        "cinnost": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "cinnost"
        },
        "zakazka": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 30,
            "fkEvidencePath": "zakazka"
        },
        "statOdesl": {
            "type": "relation",
            "maxLength": 3,
            "fkEvidencePath": "stat"
        },
        "statUrc": {
            "type": "relation",
            "maxLength": 3,
            "fkEvidencePath": "stat"
        },
        "statPuvod": {
            "type": "relation",
            "maxLength": 3,
            "fkEvidencePath": "stat"
        },
        "dodPodm": {
            "type": "relation",
            "fkEvidencePath": "intrastat-dodaci-podminky"
        },
        "obchTrans": {
            "type": "relation",
            "fkEvidencePath": "intrastat-obchodni-transakce"
        },
        "druhDopr": {
            "type": "relation",
            "fkEvidencePath": "intrastat-druh-dopravy"
        },
        "zvlPoh": {
            "type": "relation",
            "fkEvidencePath": "intrastat-zvlastni-pohyb"
        },
        "krajUrc": {
            "type": "relation",
            "fkEvidencePath": "intrastat-kraj-urceni"
        },
        "uzivatel": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "zodpOsoba": {
            "type": "relation",
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "kontaktOsoba": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "kontakt"
        },
        "kontaktJmeno": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "kontaktEmail": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "kontaktTel": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "rada": {
            "type": "relation",
            "fkEvidencePath": "rada-zavazku"
        },
        "sazbaDphOsv": {
            "type": "relation",
            "writable": false,
            "businessLogic": true,
            "fkEvidencePath": "sazba-dph"
        },
        "sazbaDphSniz": {
            "type": "relation",
            "writable": false,
            "businessLogic": true,
            "fkEvidencePath": "sazba-dph"
        },
        "sazbaDphSniz2": {
            "type": "relation",
            "writable": false,
            "businessLogic": true,
            "fkEvidencePath": "sazba-dph"
        },
        "sazbaDphZakl": {
            "type": "relation",
            "writable": false,
            "businessLogic": true,
            "fkEvidencePath": "sazba-dph"
        },
        "smlouva": {
            "type": "relation",
            "maxLength": 20,
            "fkEvidencePath": "smlouva"
        },
        "formaDopravy": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "forma-dopravy"
        },
        "uuid": {
            "type": "string",
            "writable": false,
            "maxLength": 50
        },
        "source": {
            "type": "string",
            "maxLength": 50
        },
        "clenKonVykDph": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "cleneni-kontrolni-hlaseni"
        },
        "datUp1": {
            "type": "date"
        },
        "datUp2": {
            "type": "date"
        },
        "datSmir": {
            "type": "date"
        },
        "datPenale": {
            "type": "date"
        },
        "podpisPrik": {
            "type": "logic",
            "writable": false
        },
        "prikazSum": {
            "type": "numeric",
            "writable": false
        },
        "prikazSumMen": {
            "type": "numeric",
            "writable": false
        },
        "juhSum": {
            "type": "numeric",
            "writable": false
        },
        "juhSumMen": {
            "type": "numeric",
            "writable": false
        },
        "juhDat": {
            "type": "numeric",
            "writable": false
        },
        "juhDatMen": {
            "type": "numeric",
            "writable": false
        },
        "zbyvaUhradit": {
            "type": "numeric",
            "writable": false,
            "inSummary": true
        },
        "zbyvaUhraditMen": {
            "type": "numeric",
            "writable": false,
            "inSummary": true
        },
        "formaUhradyCis": {
            "type": "relation",
            "businessLogic": true,
            "fkEvidencePath": "forma-uhrady"
        },
        "stavUhrK": {
            "type": "select",
            "businessLogic": true,
            "inSummary": true
        },
        "juhSumPp": {
            "type": "numeric"
        },
        "juhSumPpMen": {
            "type": "numeric"
        },
        "sumPrepl": {
            "type": "numeric"
        },
        "sumPreplMen": {
            "type": "numeric"
        },
        "sumZalohy": {
            "type": "numeric",
            "writable": false,
            "inSummary": true
        },
        "sumZalohyMen": {
            "type": "numeric",
            "writable": false,
            "inSummary": true
        },
        "stavOdpocetK": {
            "type": "select",
            "writable": false,
            "businessLogic": true
        },
        "zakazPlatba": {
            "type": "logic"
        },
        "sumCelkemBezZaloh": {
            "type": "numeric",
            "decimal": 2,
            "digits": 15
        },
        "sumCelkemBezZalohMen": {
            "type": "numeric",
            "decimal": 2,
            "digits": 15
        },
        "osobUpravaDph": {
            "type": "logic",
            "businessLogic": true
        }
    };

    function fetchRecord(serverConfig, evidencePath, id, callback) {
        var baseUrl  = serverConfig.url.replace(/\/$/, '');
        var company  = serverConfig.company;
        var user     = serverConfig.credentials.user     || '';
        var password = serverConfig.credentials.password || '';
        var fullUrl  = baseUrl + '/c/' + company + '/' + evidencePath + '/' + id + '.json';

        var parsed   = urlModule.parse(fullUrl);
        var protocol = parsed.protocol === 'https:' ? require('https') : require('http');
        var auth     = Buffer.from(user + ':' + password).toString('base64');

        var req = protocol.request({
            hostname:           parsed.hostname,
            port:               parsed.port,
            path:               parsed.path,
            method:             'GET',
            headers:            { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' },
            rejectUnauthorized: false
        }, function (res) {
            var data = '';
            res.on('data', function (chunk) { data += chunk; });
            res.on('end', function () {
                if (res.statusCode >= 400) {
                    callback(new Error('HTTP ' + res.statusCode + ' (' + fullUrl + ')'));
                    return;
                }
                try { callback(null, JSON.parse(data)); }
                catch (e) { callback(e); }
            });
        });
        req.on('error', callback);
        req.end();
    }

    function filterKeys(record, allowList) {
        var out = {};
        allowList.forEach(function (k) { if (k in record) out[k] = record[k]; });
        return out;
    }

    function excludeKeys(record, denyList) {
        var out = {};
        Object.keys(record).forEach(function (k) {
            if (denyList.indexOf(k) === -1) out[k] = record[k];
        });
        return out;
    }

    function AbraFlexiZavazekNode(config) {
        RED.nodes.createNode(this, config);
        var node         = this;
        var serverConfig = RED.nodes.getNode(config.server);

        node.on('input', function (msg, send, done) {
            if (!serverConfig) {
                node.error('Není nakonfigurován AbraFlexi server', msg);
                return done();
            }
            var id = String((msg.payload && msg.payload.id != null ? msg.payload.id : msg.id) || '').trim();
            if (!id) {
                node.error('Chybí msg.payload.id nebo msg.id (ID záznamu)', msg);
                return done();
            }

            node.status({ fill: 'blue', shape: 'dot', text: 'načítám ' + id });

            fetchRecord(serverConfig, 'zavazek', id, function (err, json) {
                if (err) {
                    node.error(err.message, msg);
                    node.status({ fill: 'red', shape: 'ring', text: 'chyba' });
                    return done(err);
                }
                var records = json.winstrom && json.winstrom['zavazek'];
                if (!records || records.length === 0) {
                    node.warn('Záznam nenalezen: zavazek/' + id, msg);
                    node.status({ fill: 'yellow', shape: 'ring', text: 'nenalezeno' });
                    return done();
                }
                var record = records[0];

                var outMsg                  = RED.util.cloneMessage(msg);
                outMsg.payload              = record;
                outMsg.writablePayload      = excludeKeys(record, READONLY_FIELDS);
                outMsg.summaryPayload       = filterKeys(record, SUMMARY_FIELDS);
                outMsg.schema               = SCHEMA;
                outMsg.readonlyFields       = READONLY_FIELDS;
                outMsg.mandatoryFields      = MANDATORY_FIELDS;
                outMsg.gdprFields           = GDPR_FIELDS;
                outMsg.businessLogicFields  = BUSINESS_LOGIC_FIELDS;
                outMsg.topic                = 'zavazek';
                outMsg.abraflexi_id         = record.id || id;

                var subMsg             = RED.util.cloneMessage(msg);
                subMsg.payload = record['zavazek-polozka'] || [];
                subMsg.topic   = 'zavazek-polozka';
                send([outMsg, subMsg]);
                node.status({ fill: 'green', shape: 'dot', text: record.kod || String(id) });
                done();
            });
        });

        node.status({ fill: 'grey', shape: 'ring', text: 'čeká' });
    }

    RED.nodes.registerType('abraflexi-zavazek', AbraFlexiZavazekNode);
};
