'use strict';

// Generated by tools/gen_nodes.py — do not edit by hand.
module.exports = function (RED) {
    var urlModule = require('url');

    var READONLY_FIELDS       = ["id", "lastUpdate", "pocetPriloh", "createdDate", "updatedBy", "createdBy"];
    var MANDATORY_FIELDS      = ["kod", "nazev"];
    var SUMMARY_FIELDS        = ["id", "lastUpdate", "kod", "nazev", "ulice", "mesto", "psc", "stat", "ic", "dic", "vatId"];
    var GDPR_FIELDS           = ["nazev", "nazevA", "nazevB", "nazevC", "ulice", "mesto", "psc", "tel", "mobil", "fax", "email", "faJmenoFirmy", "faUlice", "faMesto", "faPsc", "osloveni", "nazev2", "nazev2A", "nazev2B", "nazev2C", "datNaroz", "rodCis"];
    var BUSINESS_LOGIC_FIELDS = ["id", "lastUpdate", "kod", "nazev", "popis", "platiOd", "platiDo", "stat", "ic", "dic", "postovniShodna", "platceDph", "formExportK", "typVztahuK", "rodCis", "stredisko", "faStat"];
    var SCHEMA                = {
        "id": {
            "type": "integer",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "lastUpdate": {
            "type": "datetime",
            "writable": false,
            "businessLogic": true,
            "inSummary": true
        },
        "kod": {
            "type": "string",
            "mandatory": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20
        },
        "nazev": {
            "type": "string",
            "mandatory": true,
            "gdpr": true,
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 255
        },
        "nazevA": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "nazevB": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "nazevC": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "poznam": {
            "type": "string"
        },
        "popis": {
            "type": "string",
            "businessLogic": true
        },
        "platiOd": {
            "type": "integer",
            "businessLogic": true,
            "maxValue": 9999.0,
            "minValue": 0.0
        },
        "platiDo": {
            "type": "integer",
            "businessLogic": true,
            "maxValue": 9999.0,
            "minValue": 0.0
        },
        "ulice": {
            "type": "string",
            "gdpr": true,
            "inSummary": true,
            "maxLength": 255
        },
        "mesto": {
            "type": "string",
            "gdpr": true,
            "inSummary": true,
            "maxLength": 255
        },
        "psc": {
            "type": "string",
            "gdpr": true,
            "inSummary": true,
            "maxLength": 255
        },
        "tel": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "mobil": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "fax": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "email": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "www": {
            "type": "string",
            "maxLength": 255
        },
        "stat": {
            "type": "relation",
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 3,
            "fkEvidencePath": "stat"
        },
        "region": {
            "type": "relation",
            "fkEvidencePath": "region"
        },
        "eanKod": {
            "type": "string",
            "maxLength": 20
        },
        "ic": {
            "type": "string",
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20
        },
        "dic": {
            "type": "string",
            "businessLogic": true,
            "inSummary": true,
            "maxLength": 20
        },
        "vatId": {
            "type": "string",
            "inSummary": true,
            "maxLength": 20
        },
        "postovniShodna": {
            "type": "logic",
            "businessLogic": true
        },
        "faEanKod": {
            "type": "string",
            "maxLength": 20
        },
        "faJmenoFirmy": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "faUlice": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "faMesto": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "faPsc": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "splatDny": {
            "type": "integer",
            "minValue": 0.0
        },
        "limitFak": {
            "type": "numeric",
            "decimal": 2,
            "digits": 12
        },
        "limitPoSplatDny": {
            "type": "integer",
            "minValue": 0.0
        },
        "limitPoSplatZakaz": {
            "type": "logic"
        },
        "platceDph": {
            "type": "logic",
            "businessLogic": true
        },
        "formExportK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "typVztahuK": {
            "type": "select",
            "businessLogic": true,
            "maxLength": 50
        },
        "kodPojistovny": {
            "type": "string",
            "maxLength": 20
        },
        "nazevPojistovny": {
            "type": "string",
            "maxLength": 255
        },
        "osloveni": {
            "type": "string",
            "gdpr": true
        },
        "slevaDokl": {
            "type": "numeric",
            "decimal": 2,
            "digits": 6,
            "maxValue": 100.0,
            "minValue": -100.0
        },
        "obpAutomHotovo": {
            "type": "logic"
        },
        "nazev2": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "nazev2A": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "nazev2B": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "nazev2C": {
            "type": "string",
            "gdpr": true,
            "maxLength": 255
        },
        "nespolehlivyPlatce": {
            "type": "logic"
        },
        "revize": {
            "type": "integer",
            "minValue": 0.0
        },
        "stitky": {
            "type": "string"
        },
        "pocetPriloh": {
            "type": "integer",
            "writable": false
        },
        "katastrUzemi": {
            "type": "string",
            "maxLength": 255
        },
        "parcela": {
            "type": "string",
            "maxLength": 255
        },
        "datNaroz": {
            "type": "date",
            "gdpr": true
        },
        "rodCis": {
            "type": "string",
            "gdpr": true,
            "businessLogic": true,
            "maxLength": 20
        },
        "datZaloz": {
            "type": "date"
        },
        "canceled": {
            "type": "logic"
        },
        "isdocPrilohaMailuK": {
            "type": "select",
            "maxLength": 50
        },
        "createdDate": {
            "type": "datetime",
            "writable": false
        },
        "skupFir": {
            "type": "relation",
            "fkEvidencePath": "skupina-firem"
        },
        "stredisko": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 20,
            "fkEvidencePath": "stredisko"
        },
        "faStat": {
            "type": "relation",
            "businessLogic": true,
            "maxLength": 3,
            "fkEvidencePath": "stat"
        },
        "faRegion": {
            "type": "relation",
            "fkEvidencePath": "region"
        },
        "zodpOsoba": {
            "type": "relation",
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "skupCen": {
            "type": "relation",
            "fkEvidencePath": "cenikova-skupina"
        },
        "formaUhradyCis": {
            "type": "relation",
            "fkEvidencePath": "forma-uhrady"
        },
        "updatedBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        },
        "createdBy": {
            "type": "relation",
            "writable": false,
            "maxLength": 254,
            "fkEvidencePath": "uzivatel"
        }
    };

    function fetchRecord(serverConfig, evidencePath, id, callback) {
        var baseUrl  = serverConfig.url.replace(/\/$/, '');
        var company  = serverConfig.company;
        var user     = serverConfig.credentials.user     || '';
        var password = serverConfig.credentials.password || '';
        var fullUrl  = baseUrl + '/c/' + company + '/' + evidencePath + '/' + id + '.json';

        var parsed   = urlModule.parse(fullUrl);
        var protocol = parsed.protocol === 'https:' ? require('https') : require('http');
        var auth     = Buffer.from(user + ':' + password).toString('base64');

        var req = protocol.request({
            hostname:           parsed.hostname,
            port:               parsed.port,
            path:               parsed.path,
            method:             'GET',
            headers:            { 'Authorization': 'Basic ' + auth, 'Accept': 'application/json' },
            rejectUnauthorized: false
        }, function (res) {
            var data = '';
            res.on('data', function (chunk) { data += chunk; });
            res.on('end', function () {
                if (res.statusCode >= 400) {
                    callback(new Error('HTTP ' + res.statusCode + ' (' + fullUrl + ')'));
                    return;
                }
                try { callback(null, JSON.parse(data)); }
                catch (e) { callback(e); }
            });
        });
        req.on('error', callback);
        req.end();
    }

    function filterKeys(record, allowList) {
        var out = {};
        allowList.forEach(function (k) { if (k in record) out[k] = record[k]; });
        return out;
    }

    function excludeKeys(record, denyList) {
        var out = {};
        Object.keys(record).forEach(function (k) {
            if (denyList.indexOf(k) === -1) out[k] = record[k];
        });
        return out;
    }

    function AbraFlexiAdresarNode(config) {
        RED.nodes.createNode(this, config);
        var node         = this;
        var serverConfig = RED.nodes.getNode(config.server);

        node.on('input', function (msg, send, done) {
            if (!serverConfig) {
                node.error('Není nakonfigurován AbraFlexi server', msg);
                return done();
            }
            var id = String((msg.payload && msg.payload.id != null ? msg.payload.id : msg.id) || '').trim();
            if (!id) {
                node.error('Chybí msg.payload.id nebo msg.id (ID záznamu)', msg);
                return done();
            }

            node.status({ fill: 'blue', shape: 'dot', text: 'načítám ' + id });

            fetchRecord(serverConfig, 'adresar', id, function (err, json) {
                if (err) {
                    node.error(err.message, msg);
                    node.status({ fill: 'red', shape: 'ring', text: 'chyba' });
                    return done(err);
                }
                var records = json.winstrom && json.winstrom['adresar'];
                if (!records || records.length === 0) {
                    node.warn('Záznam nenalezen: adresar/' + id, msg);
                    node.status({ fill: 'yellow', shape: 'ring', text: 'nenalezeno' });
                    return done();
                }
                var record = records[0];

                var outMsg                  = RED.util.cloneMessage(msg);
                outMsg.payload              = record;
                outMsg.writablePayload      = excludeKeys(record, READONLY_FIELDS);
                outMsg.summaryPayload       = filterKeys(record, SUMMARY_FIELDS);
                outMsg.schema               = SCHEMA;
                outMsg.readonlyFields       = READONLY_FIELDS;
                outMsg.mandatoryFields      = MANDATORY_FIELDS;
                outMsg.gdprFields           = GDPR_FIELDS;
                outMsg.businessLogicFields  = BUSINESS_LOGIC_FIELDS;
                outMsg.topic                = 'adresar';
                outMsg.abraflexi_id         = record.id || id;

                send([outMsg]);
                node.status({ fill: 'green', shape: 'dot', text: record.kod || String(id) });
                done();
            });
        });

        node.status({ fill: 'grey', shape: 'ring', text: 'čeká' });
    }

    RED.nodes.registerType('abraflexi-adresar', AbraFlexiAdresarNode);
};
